languageCode = "ru"
languageName = "Русский"
weight = 1
title = "SigilGate"

[params.author]
  name = "SigilGate"
  image = "img/avatar.png"
  headline = "Свободный интернет без границ"
  links = [
    { github = "https://github.com/SigilGate" },
    { telegram = "#" },
    { discord = "#" },
  ]
