languageCode = "en"
languageName = "English"
weight = 2
title = "SigilGate"

[params.author]
  name = "Sigil Gate"
  image = "img/avatar.png"
  headline = "Building tunnels, bridging gaps, connecting people."
  links = [
    { github = "https://github.com/SigilGate" },
    { telegram = "https://t.me/SigilGate" },
    { discord = "#" },
  ]
