[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[main]]
  identifier = "appearance"
  weight = 40
  [main.params]
    action = "appearance"
    showName = false

[[main]]
  identifier = "locale"
  weight = 50
  [main.params]
    action = "locale"
    showName = false
