colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = true

[header]
  layout = "hybrid"

[footer]
  showAppearanceSwitcher = false

[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5

[article]
  showDate = true
  showReadingTime = true
  showEdit = true
  editURL = "https://github.com/SigilGate/SigilGate.github.io/tree/main/content/"
  editAppendPath = true

[social]
  github = "https://github.com/SigilGate"
