colorScheme = "congo"
defaultAppearance = "dark"
autoSwitchAppearance = false

homepage.layout = "page"
homepage.showRecent = true
homepage.recentLimit = 5

article.showDate = true
article.showReadingTime = true
article.showEdit = true
article.editURL = "https://github.com/SigilGate/SigilGate.github.io/tree/main/content/"
article.editAppendPath = true

[social]
  github = "https://github.com/SigilGate"
